name: Deploy to sandbox

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish to PROD
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.62.2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build Site
        run: hugo --baseURL https://2020.devfesttoulouse.fr/

#      - name: Generate schedule in PDF
#        run: node tools/pdf.js

      - name: Generate PWA service worker
        run: node tools/service-worker.js

      - name: Optimize HTML
        run: node tools/minify.js

      - name: Configure to PROD
        uses: w9jds/firebase-action@v1.2.0
        with:
          args: use prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_PROD_TOKEN }}

      - name: Publish to PROD
        uses: w9jds/firebase-action@v1.2.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_PROD_TOKEN }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: 08_site-applimobile
